### ISSUE TITLE
Preview of music art don't work

### ISSUE THREAD

**Issue by 0xdres** [archcraft-os/archcraft-qtile#1]
![Screenshot_2023-07-11-22-26-00_1920x1080](https://github.com/archcraft-os/archcraft-qtile/assets/101137391/7755cdf7-2c80-4303-b42a-0ba75b9a7cde)

I tried to reinstall ueberzug and check settings but still the same, it doesn't show music art, also when trying to play a new music the player freezes and doesn't work anymore.

**Comment by adi1090x** [comment]
It's been fixed a long time ago.
